// Run against a local Migration preview. All endpoints and identities are synthetic fixtures.
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--disable-gpu']});
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let historyFixture=false, journalFixture=false, journalFails=false, slowJournal=false;
  const journalRequests=[];
  const userErrors=Array.from({length:201},(_,i)=>({id:i+1,entity_type:'users',legacy_id:`synthetic-user-${i+1}`,severity:'error',code:'SOURCE_ROW_UNRESOLVED',message:`Synthetic missing employee login ${i+1}`,created_at:'2026-10-07T00:00:00Z'}));
  const laterWarnings=Array.from({length:200},(_,i)=>({id:1000+i,entity_type:'activity_log',legacy_id:`synthetic-log-${i}`,severity:'warning',message:'Synthetic metadata warning',created_at:'2026-10-07T00:01:00Z'}));
  let polls=0, starts=0, forbidden=false, verifyFails=true, restoreFails=true;
  const deleted=[], restored=[], created=[];let manualCheckpoint=null, backupPause=false, backupPauseStatus=502, ordinaryOutage=false;
  const checkpoints={all:[{id:'100',scope:'all',created_at:'2026-10-07T00:00:00Z',restored:false}],employees:[{id:'401',scope:'employees',created_at:'2026-10-07T00:00:00Z',restored:false}],vacations:[{id:'602',scope:'vacations',created_at:'2026-10-07T00:00:00Z',restored:true}],clients:[],timesheets:[]};
  const legacy={employees:[{id:'201',created_at:'2026-10-06T00:00:00Z',restored:false}],vacations:[{id:'603',created_at:'2026-10-06T00:00:00Z',restored:false}]};
  const issuer='http://127.0.0.1:5173/keycloak/auth/realms/irlix';
  await page.addInitScript(({issuer})=>{
    const payload=btoa(JSON.stringify({iss:issuer,exp:Math.floor(Date.now()/1000)+3600,name:'Synthetic Operator'}));
    sessionStorage.setItem('irlix.migration.auth.tokens',JSON.stringify({access_token:`e30.${payload}.synthetic`}));
  },{issuer});
  const profile=()=>({host:`server-poll-${polls}.invalid`,port:5432,database:'synthetic',username:'readonly_test',sslmode:'disable',readonly_acknowledged:true,verified_at:'2026-10-07 00:00:00',credential_status:'ready'});
  await page.route('**/.well-known/openid-configuration',r=>r.fulfill({json:{issuer,authorization_endpoint:issuer+'/auth',token_endpoint:issuer+'/token'}}));
  await page.route('**/api/employees/access/me',r=>r.fulfill({json:{data:{roles:forbidden?[]:['platform-admin']}}}));
  await page.route('**/api/migration/**',async r=>{
    const path=new URL(r.request().url()).pathname;
    if((ordinaryOutage || (backupPause && manualCheckpoint?.status==='running')) && r.request().method()==='GET') return r.fulfill({status:backupPauseStatus,contentType:'text/html',body:'<h1>Synthetic API maintenance</h1>'});
    if(path==='/api/migration/console/runs/7' && new URL(r.request().url()).searchParams.get('operation_id')==='8008') return r.fulfill({status:404,json:{message:'Подробный отчёт этой операции недоступен после восстановления метаданных. Запись истории сохранена.'}});
    if(path==='/api/migration/state') {polls++;return r.fulfill({json:{data:{modules:[{key:'employees',status:'implemented',dependencies:[],connection:profile(),latest_run:{id:7,status:'completed',mode:'migrate'}},{key:'vacations',status:'implemented',dependencies:['employees'],connection:profile(),latest_run:journalFixture?{id:8,status:'conflicts',mode:'dry-run'}:null},{key:'clients',status:'implemented',dependencies:['employees'],connection:profile()},{key:'timesheets',status:'implemented',dependencies:['employees','clients'],connection:profile()},{key:'specialists',status:'planned',dependencies:['employees'],description:'Synthetic future module'}],recent_runs:[]}}});}
    if(path==='/api/migration/console/state') return r.fulfill({json:{data:{operation:starts?{id:'synthetic-42',status:'queued',phase:'queued',scope:'all',runs:[],services:['employees','vacations'],message:'Ожидает запуска'}:manualCheckpoint,history:historyFixture?[{id:'8008',scope:'vacations',action:'migrate',status:'failed',runs:[{id:7,service:'vacations',mode:'dry-run',status:'conflicts'}],message:'Synthetic failed history'},{id:'8009',scope:'employees',action:'snapshot',status:'completed',services:['employees'],runs:[],message:'Synthetic employee snapshot'}]:[],snapshots:checkpoints,snapshot_operation:{state:'idle'}}}});
    if(r.request().method()==='DELETE'&&path.includes('/snapshots/')) {
      deleted.push(path);const id=path.split('/').at(-1);
      const items=path.includes('/console/')?checkpoints[path.split('/').at(-2)]:legacy[path.includes('/vacations/')?'vacations':'employees'];
      items.splice(items.findIndex(item=>item.id===id),1);return r.fulfill({json:{data:{deleted:true}}});
    }
    if(path==='/api/migration/snapshots'||path==='/api/migration/vacations/snapshots') return r.fulfill({json:{data:{snapshots:legacy[path.includes('/vacations/')?'vacations':'employees'],operation:{state:'idle'}}}});
    if(path==='/api/migration/console/snapshot') {
      const body=r.request().postDataJSON();created.push(body);
      manualCheckpoint={id:'synthetic-backup-'+created.length,status:backupPause?'running':'completed',phase:'snapshot',action:'snapshot',scope:body.scope,message:'Точка отката создана'};
      checkpoints[body.scope].push({id:'999',scope:body.scope,created_at:'2026-10-07T01:00:00Z',restored:false});
      return r.fulfill({status:202,json:{data:{operation:manualCheckpoint}}});
    }
    if(path==='/api/migration/console/restore'||path.endsWith('/restore')) {
      restored.push({path,body:r.request().postDataJSON()});
      if(restoreFails)return r.fulfill({status:409,json:{message:'Synthetic restore blocked'}});
      return r.fulfill({status:202,json:{data:{operation:{id:'synthetic-restore',status:'completed',state:'completed',action:'restore',scope:r.request().postDataJSON().scope}}}});
    }
    if(path==='/api/migration/console/runs/8') return r.fulfill({json:{data:{id:8,status:'conflicts',mode:'dry-run',conflict_count:201,warning_count:200,tables:[{table_name:'users',state:'checked',processed_count:201,total:201,error_count:201,warning_count:0}],events:[],conflicts:laterWarnings,conflicts_more:true,conflict_cursor:1000}}});
    if(path.endsWith('/conflicts')) {
      const url=new URL(r.request().url());journalRequests.push(url);
      if(journalFails) return r.fulfill({status:503,json:{message:'Synthetic journal unavailable'}});
      if(slowJournal && url.searchParams.get('severity')==='error') await new Promise(resolve=>setTimeout(resolve,500));
      let items=path.includes('/runs/8/')?[...userErrors,...laterWarnings]:[{id:81,entity_type:'employment',legacy_id:'13',severity:'error',code:'OPEN_PERIOD_ALREADY_EXISTS',message:'Synthetic period conflict',created_at:'2026-10-07T00:00:00Z'}];
      const table=url.searchParams.get('table'),kind=url.searchParams.get('severity'),before=url.searchParams.get('before');
      if(table) items=items.filter(item=>item.entity_type===table || table==='employees' && item.entity_type==='employee');
      if(kind) items=items.filter(item=>item.severity===kind);
      const total=items.length;
      items=items.filter(item=>!before || item.id<Number(before)).sort((a,b)=>b.id-a.id);
      const pageItems=items.slice(0,200);
      return r.fulfill({json:{data:{items:pageItems,more:items.length>200,cursor:pageItems.at(-1)?.id||null,total}}});
    }
    if(path==='/api/migration/console/runs/7') return r.fulfill({json:{data:{id:7,status:'completed',mode:'migrate',processed_count:20,success_count:19,conflict_count:1,warning_count:0,tables:[{table_name:'employees',state:'conflicts',processed_count:20,total:20,success_count:19,error_count:1,warning_count:0}],events:[{id:1,level:'error',message:'Synthetic import conflict',context:{table:'employees'},created_at:'2026-10-07T00:00:00Z'}],conflicts:[{id:81,entity_type:'employment',legacy_id:'13',severity:'error',code:'OPEN_PERIOD_ALREADY_EXISTS',message:'Synthetic period conflict',context:{},created_at:'2026-10-07T00:00:00Z'}]}}});
    if(path==='/api/migration/console/conflicts/81/details') return r.fulfill({json:{data:{basis:'current',details:{observed_at:'2026-10-07T01:00:00Z',employee:{legacy_id:'synthetic-employee',target_id:9,full_name:'Operator Synthetic',login:'synthetic.operator'},source_period:{id:13,cooperation_type:'Synthetic cooperation',started_at:'2026-02-01',ended_at:null},target_open_periods:[{id:11,cooperation_type:'Synthetic cooperation',started_at:'2026-01-01',ended_at:null}]}}}});
    if(path.endsWith('/verify')) return r.fulfill(verifyFails?{status:422,json:{message:'Synthetic DB connection error'}}:{json:{data:{}}});
    if(path==='/api/migration/console/start') {starts++;return r.fulfill({json:{data:{operation:{id:'synthetic-42',status:'queued',phase:'queued',scope:'all',runs:[],services:['employees','vacations']}}},status:202});}
    return r.fulfill({json:{data:{}},status:200});
  });
  await page.goto(new URL('/migration/', process.env.MIGRATION_PREVIEW || 'http://127.0.0.1:5173/').href);
  assert.equal(await page.locator('.icon-nav').getByRole('button',{name:'Дашборд',exact:true}).count(),0,'migration owns its navigation');
  const consoleMenu=page.locator('.icon-nav').getByRole('button',{name:'Пульт переноса',exact:true});
  await page.getByRole('button',{name:'Перенести все',exact:true}).waitFor();
  assert.equal(new URL(page.url()).pathname,'/migration/','console opens directly on the main page');
  assert.equal(await page.getByRole('button',{name:'Текущий интерфейс',exact:true}).count(),0,'legacy navigation is removed');
  assert.equal(await page.locator('#migration-page, #migration-modules').count(),0,'legacy page is removed');
  assert.equal(await consoleMenu.evaluate(button=>button.classList.contains('active')),true,'console menu is active on its page');
  await page.getByRole('button',{name:'Перенести все',exact:true}).waitFor();
  await page.getByRole('button',{name:/01 Сотрудники/}).click();
  await page.getByRole('button',{name:'Сотрудник и периоды · ошибка 81',exact:true}).click();
  const diagnostics=page.locator('.irlix-drawer').filter({hasText:'Сотрудник и конфликтующие периоды'});
  await diagnostics.getByText('Operator Synthetic',{exact:true}).waitFor();
  assert.ok((await diagnostics.innerText()).includes('Текущие данные БД'));
  assert.ok((await diagnostics.innerText()).includes('2026-02-01') && (await diagnostics.innerText()).includes('2026-01-01'),'Source and target dates visible');
  await diagnostics.getByRole('button',{name:'Закрыть',exact:true}).click();
  const panes=await page.evaluate(()=>{const a=document.querySelector('.mc-tables').getBoundingClientRect(),b=document.querySelector('.mc-log').getBoundingClientRect();return {left:a.x,right:b.x,topA:a.y,topB:b.y,widthA:a.width,widthB:b.width};});
  assert.equal(panes.topA,panes.topB,'panes share top edge');
  assert.ok(panes.right>panes.left&&Math.abs(panes.widthA-panes.widthB)<1,'equal side-by-side panes');
  assert.equal(await page.locator('.mc-progress').getByRole('button',{name:'Перенести',exact:true}).count(),1,'actions in phases panel');
  assert.equal(await page.getByRole('button',{name:'Обновить',exact:true}).count(),0,'no redundant refresh button');
  assert.deepEqual(await page.locator('.mc-table thead th').allTextContents(),['Сервис / таблица','Состояние','Обработано / всего','Успешно / Ошибки / Предупр.']);
  const imported=page.locator('.mc-table tbody tr').filter({has:page.locator('.mc-table-name')});
  assert.equal(await imported.locator('td').count(),4,'merged counter column');
  assert.equal((await imported.locator('.mc-counts').innerText()).replace(/\s/g,''),'19/1/0','counter order and values');
  assert.ok(await page.locator('.mc-table').evaluate(table=>[...table.rows].every(row=>[...row.cells].slice(1).every(cell=>getComputedStyle(cell).textAlign==='center'))),'all non-name columns centered');
  assert.equal(await page.locator('.mc-table thead th').first().evaluate(cell=>getComputedStyle(cell).textAlign),'left','name column stays left aligned');
  await imported.getByRole('button',{name:'Ошибки · employees',exact:true}).click();
  assert.match(await page.locator('.mc-log-filter').innerText(),/employees/,'error counter filters table log');
  assert.equal(await page.locator('.mc-log-filters').getByRole('button',{name:'Ошибки',exact:true}).getAttribute('aria-pressed'),'true');
  await imported.getByRole('button',{name:'Предупреждения · employees',exact:true}).click();
  assert.equal(await page.locator('.mc-log-filters').getByRole('button',{name:'Предупреждения',exact:true}).getAttribute('aria-pressed'),'true');
  await page.locator('.mc-log-filter').getByRole('button',{name:'Сбросить',exact:true}).click();
  await page.locator('.mc-log-filters').getByRole('button',{name:'Все',exact:true}).click();
  const density=await page.locator('.mc-table-name').evaluate(td=>({height:td.parentElement.getBoundingClientRect().height,font:getComputedStyle(td).fontSize}));
  assert.ok(density.height<=34,'compact table row');assert.equal(density.font,'12px','table font unchanged');
  assert.ok(await page.locator('.mc-log-filters button').first().evaluate(b=>b.getBoundingClientRect().height)<=27,'compact filters');
  assert.ok(await page.locator('.mc-log-head label').evaluate(label=>{const a=label.getBoundingClientRect(),b=label.querySelector('input').getBoundingClientRect();return Math.abs(a.y+a.height/2-b.y-b.height/2)<1;}),'checkbox vertically centered');
  const headers=()=>page.evaluate(()=>{const a=document.querySelector('.mc-section-title').getBoundingClientRect(),b=document.querySelector('.mc-log-head').getBoundingClientRect();return {a:a.y,b:b.y,ha:a.height,hb:b.height};});
  assert.deepEqual(await headers(),{a:panes.topA,b:panes.topA,ha:(await headers()).ha,hb:(await headers()).ha},'one aligned header row');
  assert.ok(await page.evaluate(()=>{const a=document.querySelector('.mc-progress-copy').getBoundingClientRect(),b=document.querySelector('.mc-progress>.mc-actions').getBoundingClientRect();return b.x>=a.right;}),'actions on right of text');
  assert.equal(await page.getByText('Очередь переноса',{exact:true}).count(),0,'no queue heading');
  assert.ok(await page.locator('.mc-service').first().evaluate(b=>getComputedStyle(b).borderRadius==='0px'&&getComputedStyle(b).borderBottomWidth==='0px'),'plain service tabs');
  const divider=page.getByRole('separator',{name:'Ширина таблицы переноса'});
  const rect=await divider.boundingBox();await page.mouse.move(rect.x+0.5,rect.y+50);await page.mouse.down();await page.mouse.move(rect.x+150,rect.y+50);await page.mouse.up();
  assert.ok(Number(await divider.getAttribute('aria-valuenow'))>50,'pointer resizes panes');
  await divider.focus();await divider.press('End');assert.equal(await divider.getAttribute('aria-valuenow'),'80');
  const narrow=await headers();assert.equal(narrow.ha,narrow.hb,'headers align after resizing');
  await divider.dblclick();assert.equal(await divider.getAttribute('aria-valuenow'),'50','double click restores halves');
  await divider.focus();await divider.press('ArrowRight');assert.equal(await divider.getAttribute('aria-valuenow'),'52','keyboard resizes panes');
  const columns=await page.evaluate(()=>{const a=document.querySelector('.mc-table thead').getBoundingClientRect(),b=document.querySelector('.mc-log thead').getBoundingClientRect();return {a:a.y,b:b.y,ha:a.height,hb:b.height};});
  assert.equal(columns.a,columns.b,'column header rows share top');assert.equal(columns.ha,columns.hb,'column header rows share height');
  await divider.hover();assert.ok(await divider.evaluate(d=>d.getBoundingClientRect().width===1&&getComputedStyle(d).outlineStyle==='none'),'plain one-pixel divider on hover');
  const gear=page.getByRole('button',{name:'Настройки БД · Отпуска',exact:true}),disk=page.getByRole('button',{name:'Бэкапы · Отпуска',exact:true});
  const item=gear.locator('xpath=../..');const originalBackground=await item.evaluate(e=>getComputedStyle(e).backgroundColor);
  await gear.hover();assert.equal(await item.evaluate(e=>getComputedStyle(e).backgroundColor),originalBackground,'gear hover cannot highlight service');
  assert.equal(await gear.evaluate(e=>e.classList.contains('ui-button--secondary')),true,'gear has icon-only hover border');
  await disk.hover();assert.equal(await item.evaluate(e=>getComputedStyle(e).backgroundColor),originalBackground,'disk hover cannot highlight service');
  assert.equal(await disk.evaluate(e=>e.classList.contains('ui-button--secondary')),true,'disk has icon-only hover border');
  assert.equal(await disk.innerText(),'','backup button has no text');
  assert.equal(await disk.locator('svg use').count(),1,'disk is an SVG asset');
  const g=await gear.boundingBox(),d=await disk.boundingBox();assert.equal(g.x,d.x,'icons form one column');assert.ok(d.y>=g.y+g.height,'disk below gear');
  journalFixture=true;
  await page.reload();
  await page.getByRole('button',{name:/02 Отпуска/}).click();
  await page.getByRole('button',{name:'Ошибки · users',exact:true}).click();
  await page.getByText('Synthetic missing employee login 201',{exact:false}).waitFor();
  assert.ok(journalRequests.some(url=>url.pathname.endsWith('/runs/8/conflicts') && url.searchParams.get('severity')==='error' && url.searchParams.get('table')==='users'),'click requests matching server page');
  await page.getByText('По фильтру загружено 200 из 201 сообщений запуска #8.',{exact:false}).waitFor();
  assert.equal(await page.locator('.mc-log tbody tr.error').count(),200,'older errors are visible without loading intervening warnings');
  await page.getByRole('button',{name:'Загрузить ещё',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.mc-log tbody tr.error').length===201);
  assert.equal(await page.locator('.mc-log tbody tr.error').count(),201,'filtered pagination has no duplicates or loss');
  const requestsAfterPage=journalRequests.length;
  await page.waitForTimeout(1100);
  assert.equal(await page.locator('.mc-log tbody tr.error').count(),201,'poll retains loaded matching pages');
  assert.equal(journalRequests.length,requestsAfterPage,'unchanged run does not refetch journal');
  await page.locator('.mc-log-filters').getByRole('button',{name:'Предупреждения',exact:true}).click();
  await page.getByText('По выбранному фильтру сообщений не найдено.',{exact:true}).waitFor();
  slowJournal=true;
  await page.locator('.mc-log-filters').getByRole('button',{name:'Ошибки',exact:true}).click();
  await page.getByText('Загружаем сообщения по выбранному фильтру…',{exact:true}).waitFor();
  await page.locator('.mc-log-filters').getByRole('button',{name:'Предупреждения',exact:true}).click();
  await page.waitForTimeout(700);
  assert.equal(await page.locator('.mc-log tbody tr.error').count(),0,'late previous filter cannot replace selected filter');
  journalFails=true;slowJournal=false;
  await page.locator('.mc-log-filters').getByRole('button',{name:'Ошибки',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Synthetic journal unavailable'}).waitFor();
  assert.equal(await page.locator('.mc-main > .mc-alert.error').count(),0,'journal failure stays in journal');
  assert.equal(await page.getByText('По выбранному фильтру сообщений не найдено.',{exact:true}).count(),0,'request error cannot appear as empty result');
  journalFails=false;
  await page.getByRole('button',{name:'Повторить',exact:true}).click();
  await page.getByText('Synthetic missing employee login 201',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Настройки БД · Отпуска',exact:true}).click();
  const journalForm=page.getByLabel('Хост',{exact:true});
  await journalForm.fill('synthetic-journal-draft.invalid');
  await journalForm.evaluate(input=>input.setSelectionRange(3,8));
  await page.waitForTimeout(1100);
  assert.equal(await journalForm.inputValue(),'synthetic-journal-draft.invalid','journal requests and polling preserve connection draft');
  assert.equal(await journalForm.evaluate(input=>document.activeElement===input && input.selectionStart===3 && input.selectionEnd===8),true,'focus and caret preserved');
  await page.getByRole('button',{name:'Закрыть',exact:true}).last().click();
  journalFixture=false;
  await page.reload();
  await page.getByRole('button',{name:/01 Сотрудники/}).click();
  await divider.focus();await divider.press('ArrowRight');
  await page.screenshot({path:`${process.env.SCREENSHOT_DIR||'/tmp'}/migration-console-desktop.png`});
  await page.getByRole('button',{name:'Настройки БД · Сотрудники',exact:true}).click();
  const host=page.getByLabel('Хост',{exact:true});
  await host.fill('my-draft.invalid');
  await host.focus();
  await host.evaluate(input=>{input.setSelectionRange(3,3);window.__draftInput=input;});
  const pollStart=polls;
  assert.equal(await page.getByText(/Обновлено \d/).count(),0,'no refreshed timestamp');
  await new Promise(resolve=>setTimeout(resolve,11000));
  assert.ok(polls>=pollStart+2,'at least two background updates while editing');
  assert.equal(await divider.getAttribute('aria-valuenow'),'52','polling preserves pane widths');
  assert.equal(await host.inputValue(),'my-draft.invalid','polling cannot overwrite draft');
  assert.equal(await host.evaluate(input=>input===window.__draftInput),true,'input DOM must be retained');
  assert.equal(await host.evaluate(input=>document.activeElement===input),true,'focus survives polling');
  assert.equal(await host.evaluate(input=>input.selectionStart),3,'caret survives polling');
  await page.screenshot({path:process.env.SCREENSHOT_DIR?`${process.env.SCREENSHOT_DIR}/migration-console-form.png`:'/tmp/migration-console-form.png'});
  await page.getByRole('button',{name:'Проверить подключение',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Synthetic DB connection error'}).waitFor();
  assert.equal(await page.locator('.mc-main .mc-alert').count(),0,'DB failure is confined to drawer');
  verifyFails=false;
  await page.getByRole('button',{name:'Проверить подключение',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Read-only подключение проверено.'}).waitFor();
  assert.equal(await page.locator('.mc-main .mc-alert').count(),0,'DB success is confined to drawer');
  await page.getByRole('button',{name:'Закрыть',exact:true}).last().click();
  assert.equal(await page.locator('.mc-alert').count(),0,'DB messages do not leak after closing drawer');
  await page.getByRole('button',{name:'Бэкапы · Сотрудники',exact:true}).click();
  await page.locator('.mc-backup').filter({hasText:'#401'}).waitFor();
  await page.locator('.mc-backup').filter({hasText:'#201'}).waitFor();
  assert.match(await page.locator('.mc-help').last().innerText(),/502\/503.*ожидаемы/,'backup explains planned API pause before start');
  backupPause=true;
  await page.getByRole('button',{name:'Создать точку отката',exact:true}).click();
  await page.locator('.mc-main [role="status"]').filter({hasText:'Это ожидаемый этап бэкапа.'}).waitFor();
  assert.equal(await page.locator('.mc-main [role="alert"]').count(),0,'expected 502 is informational');
  assert.equal(await page.getByRole('button',{name:'Создать точку отката',exact:true}).isDisabled(),true,'pause keeps actions locked');
  backupPauseStatus=503;
  await page.locator('.mc-main [role="status"]').filter({hasText:'(503)'}).waitFor();
  backupPauseStatus=500;
  await page.locator('.mc-main [role="alert"]').filter({hasText:'(500)'}).waitFor();
  assert.equal(await page.locator('.mc-main [role="status"]').filter({hasText:'Это ожидаемый этап бэкапа.'}).count(),0,'unexpected server failure stays an error');
  backupPause=false;manualCheckpoint.status='completed';
  await page.getByText('Точка отката создана и проверена.',{exact:true}).waitFor();
  assert.equal(await page.locator('.mc-main .mc-alert').count(),0,'maintenance message clears after recovery');
  ordinaryOutage=true;backupPauseStatus=502;
  await page.locator('.mc-main [role="alert"]').filter({hasText:'(502)'}).waitFor();
  assert.equal(await page.locator('.mc-main [role="status"]').filter({hasText:'Это ожидаемый этап бэкапа.'}).count(),0,'502 outside active backup remains an error');
  ordinaryOutage=false;
  await page.locator('.mc-main [role="alert"]').waitFor({state:'hidden'});
  await page.locator('.mc-backup').filter({hasText:'#999'}).waitFor();
  assert.equal(created.at(-1).scope,'employees','manual backup uses drawer service');assert.equal(starts,0,'backup creation never starts import');
  await page.locator('.mc-backup').filter({hasText:'#401'}).getByRole('button',{name:'Удалить',exact:true}).click();
  assert.equal(deleted.length,0,'delete requires confirmation');
  await page.getByRole('button',{name:'Удалить бэкап',exact:true}).click();
  await page.getByText('Бэкап #401 удалён.',{exact:true}).waitFor();
  await page.locator('.mc-backup').filter({hasText:'#401'}).waitFor({state:'hidden'});
  assert.deepEqual(deleted,['/api/migration/console/snapshots/employees/401']);
  assert.equal(await page.locator('.mc-backup').filter({hasText:'#401'}).count(),0,'removed console backup vanishes');
  await page.locator('.mc-backup').filter({hasText:'#201'}).getByRole('button',{name:'Удалить',exact:true}).click();
  await page.getByRole('button',{name:'Удалить бэкап',exact:true}).click();
  await page.getByText('Бэкап #201 удалён.',{exact:true}).waitFor();
  assert.equal(deleted.at(-1),'/api/migration/snapshots/201','legacy backup uses existing API');
  await page.getByRole('button',{name:'Закрыть',exact:true}).last().click();
  await page.getByRole('button',{name:'Бэкапы · Отпуска',exact:true}).click();
  await page.getByRole('button',{name:'Создать точку отката',exact:true}).click();
  assert.equal(created.at(-1).scope,'vacations','drawer scope remains independent from active service');
  await page.locator('.mc-backup').filter({hasText:'#602'}).getByRole('button',{name:'Вернуться',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Восстановить бэкап',exact:true}).isDisabled(),true,'restore requires exact phrase');
  await page.getByLabel('Введите RESTORE VACATIONS',{exact:true}).fill('RESTORE VACATIONS');
  await page.getByRole('button',{name:'Восстановить бэкап',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Synthetic restore blocked'}).waitFor();
  assert.equal(await page.locator('.mc-main .mc-alert').count(),0,'restore error confined to backup drawer');
  assert.equal(restored.at(-1).body.scope,'vacations','backup scope independent from selected service');
  restoreFails=false;
  await page.getByRole('button',{name:'Восстановить бэкап',exact:true}).click();
  await page.getByRole('button',{name:'Бэкапы · Отпуска',exact:true}).click();
  await page.locator('.mc-backup').filter({hasText:'#603'}).getByRole('button',{name:'Вернуться',exact:true}).click();
  await page.getByLabel('Введите RESTORE VACATIONS',{exact:true}).fill('RESTORE VACATIONS');
  await page.getByRole('button',{name:'Восстановить бэкап',exact:true}).click();
  assert.equal(restored.at(-1).path,'/api/migration/vacations/snapshots/603/restore');
  assert.equal(await page.getByRole('button',{name:'Настройки БД · Специалисты',exact:true}).isDisabled(),true,'planned module settings disabled');
  for(const [name,scope] of [['Клиенты','clients'],['Таймшиты','timesheets']]) {
    assert.equal(await page.getByRole('button',{name:'Настройки БД · '+name,exact:true}).isDisabled(),false,'new service settings available');
    await page.getByRole('button',{name:'Бэкапы · '+name,exact:true}).click();
    await page.getByRole('button',{name:'Создать точку отката',exact:true}).click();
    await page.getByText('Точка отката создана и проверена.',{exact:true}).waitFor();
    assert.equal(created.at(-1).scope,scope,'new service has independent checkpoint');
    await page.getByRole('button',{name:'Закрыть',exact:true}).last().click();
  }
  await page.getByRole('button',{name:/Все сервисы Доступ проверен/}).click();
  assert.equal(await page.locator('.mc-scope-ready').count(),0,'no repeated connection summary in all services');
  assert.equal(await page.locator('.mc-live').count(),0,'no polling timestamp in any service');
  await page.getByRole('button',{name:'Перенести все',exact:true}).click();
  await page.getByRole('button',{name:'Создать точку и перенести',exact:true}).click();
  await page.waitForTimeout(150);
  assert.equal(starts,1,'one start request');
  assert.equal(await page.getByRole('button',{name:'Перенести все',exact:true}).isDisabled(),true,'queued operation stays locked');
  await page.getByRole('button',{name:'Бэкапы · Все сервисы',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Создать точку отката',exact:true}).isDisabled(),true,'active queue blocks manual checkpoint');
  assert.equal(await page.locator('.mc-backup').getByRole('button',{name:'Удалить',exact:true}).first().isDisabled(),true,'active queue blocks backup deletion');
  await page.getByRole('button',{name:'Закрыть',exact:true}).last().click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:process.env.SCREENSHOT_DIR?`${process.env.SCREENSHOT_DIR}/migration-console-mobile.png`:'/tmp/migration-console-mobile.png'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no document horizontal overflow on mobile');
  for (const oldPath of ['/migration/console','/migration/console/']) {
    await page.goto(new URL(oldPath+'?service=employees#backups', process.env.MIGRATION_PREVIEW || 'http://127.0.0.1:5173/').href);
    await page.getByRole('button',{name:'Перенести',exact:true}).waitFor();
    const canonical=new URL(page.url());
    assert.equal(canonical.pathname,'/migration/','old console route opens the main page');
    assert.equal(canonical.search,'?service=employees','service parameter survives');
    assert.equal(canonical.hash,'#backups','hash survives');
  }
  historyFixture=true;
  await page.reload();
  await page.locator('.mc-service-all .mc-service').click();
  await page.getByRole('button',{name:'История',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Открыть',exact:true}).count(),2,'all services shows complete history');
  await page.getByRole('button',{name:'Закрыть',exact:true}).last().click();
  await page.getByRole('button',{name:/02 Отпуска/}).click();
  await page.getByRole('button',{name:'История',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Открыть',exact:true}).count(),1,'vacations history excludes employee-only operation');
  await page.getByRole('button',{name:'Открыть',exact:true}).click();
  await page.locator('.mc-failure').filter({hasText:'Подробный отчёт этой операции недоступен'}).waitFor();
  assert.equal(new URL(page.url()).searchParams.get('service'),'vacations','history selects its own service');
  assert.equal(await page.locator('.mc-log-filter').count(),0,'history clears stale table filter');
  assert.equal(await page.locator('.mc-log-filters').getByRole('button',{name:'Ошибки',exact:true}).getAttribute('aria-pressed'),'true','failed history opens errors');
  forbidden=true;
  await page.reload();
  await page.getByText('Требуется роль platform-admin',{exact:true}).waitFor();
  assert.equal(await page.locator('.mc-root').count(),0,'no unauthorized console');
  assert.deepEqual(errors,[],'no runtime errors');
  console.log('Browser checks passed: polling preserves value, DOM, focus and caret; aligned headers, resizing, backup delete/restore, queue lock, mobile layout, admin access.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
