<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { UiAppShell, UiBadge, UiButton, UiPageHeader, UiPanel } from '@irlix/ui';
import { auth } from './auth';
const sections=[{id:'registry',label:'Техника',href:'/equipment/'},{id:'assignments',label:'Выдачи',href:'/equipment/assignments'},{id:'depreciation',label:'Амортизация',href:'/equipment/depreciation'},{id:'written-off',label:'Списанная техника',href:'/equipment/written-off'}];
const pathSection=()=>location.pathname.includes('/assignments')?'assignments':location.pathname.includes('/depreciation')?'depreciation':location.pathname.includes('/written-off')?'written-off':'registry';
const section=ref(pathSection()),items=ref([]),assignments=ref([]),depreciation=ref([]),permissions=reactive({view:false,manage:false,operate:false}),loading=ref(false),error=ref(''),search=ref(''),typeFilter=ref('');
const editor=reactive({open:false,id:null,inventory_number:'',type:'laptop',manufacturer:'',model:'',serial_number:'',purpose:'development',condition:'ok',comment:'',purchased_on:'',purchase_cost:'',useful_life_months:36,cpu:'',ram:'',storage:'',gpu:'',os:'',os_version:'',imei:''});
const assignment=reactive({open:false,item:null,employee_id:'',starts_on:new Date().toISOString().slice(0,10),planned_ends_on:'',issue_comment:''});
const labels={pc:'ПК',laptop:'Ноутбук',smartphone:'Смартфон',tablet:'Планшет',development:'Разработка',management_qa:'Менеджмент + QA',qa:'QA',management:'Менеджмент',ok:'Исправно',damaged:'Повреждено',needs_repair:'Требует ремонта'};
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(Number(v||0));
const filtered=computed(()=>items.value.filter(x=>(!typeFilter.value||x.type===typeFilter.value)&&(!search.value||`${x.inventory_number} ${x.manufacturer} ${x.model} ${x.serial_number||''}`.toLowerCase().includes(search.value.toLowerCase()))));
const api=async(url,opt={})=>{const r=await fetch(url,opt);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||`HTTP ${r.status}`);return b.data;};
const load=async()=>{loading.value=true;error.value='';try{Object.assign(permissions,await api('/api/permissions'));if(section.value==='assignments')assignments.value=await api('/api/assignments');else if(section.value==='depreciation')depreciation.value=await api('/api/depreciation');else items.value=await api(`/api/items?${section.value==='written-off'?'written_off=1':''}`);}catch(e){error.value=e.message;}finally{loading.value=false;}};
const changeSection=s=>{section.value=s;const href=sections.find(x=>x.id===s)?.href||'/equipment/';history.pushState({},'',href);load();};
const resetEditor=()=>Object.assign(editor,{open:false,id:null,inventory_number:'',type:'laptop',manufacturer:'',model:'',serial_number:'',purpose:'development',condition:'ok',comment:'',purchased_on:'',purchase_cost:'',useful_life_months:36,cpu:'',ram:'',storage:'',gpu:'',os:'',os_version:'',imei:''});
const openEditor=item=>{resetEditor();if(item)Object.assign(editor,item,{open:true,purchase_cost:item.purchase_cost??'',useful_life_months:item.useful_life_months??36});else editor.open=true;};
const saveItem=async()=>{const payload={};for(const k of ['inventory_number','type','manufacturer','model','serial_number','purpose','condition','comment','purchased_on','purchase_cost','useful_life_months','cpu','ram','storage','gpu','os','os_version','imei'])payload[k]=editor[k]===''?null:editor[k];await api(editor.id?`/api/items/${editor.id}`:'/api/items',{method:editor.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});resetEditor();load();};
const openAssign=item=>Object.assign(assignment,{open:true,item,employee_id:'',starts_on:new Date().toISOString().slice(0,10),planned_ends_on:'',issue_comment:''});
const assignItem=async()=>{await api(`/api/items/${assignment.item.id}/assign`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employee_id:Number(assignment.employee_id),starts_on:assignment.starts_on,planned_ends_on:assignment.planned_ends_on||null,issue_comment:assignment.issue_comment||null})});assignment.open=false;load();};
const returnItem=async item=>{const date=prompt('Дата возврата (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!date)return;await api(`/api/items/${item.id}/return`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returned_on:date})});load();};
const writeOff=async item=>{const reason=prompt('Причина списания');if(!reason)return;const date=prompt('Дата списания (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!date)return;await api(`/api/items/${item.id}/write-off`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({written_off_on:date,reason})});load();};
onMounted(()=>{window.addEventListener('popstate',()=>{section.value=pathSection();load();});load();});
watch(section,()=>{search.value='';typeFilter.value='';});
</script>
<template>
<UiAppShell service="equipment" service-name="Учёт техники" :section="section" :items="sections" :current-user="auth.user" :loading="loading" @update:section="changeSection" @logout="auth.logout">
<main class="page"><UiPageHeader :title="sections.find(x=>x.id===section)?.label || 'Учёт техники'" subtitle="Корпоративная техника, выдачи и стоимость"><template #actions><UiButton v-if="permissions.manage && (section==='registry'||section==='written-off')" @click="openEditor(null)">Добавить технику</UiButton></template></UiPageHeader>
<div v-if="error" class="error">{{error}}</div>
<UiPanel v-if="section==='registry'||section==='written-off'" class="panel"><div class="filters"><input v-model="search" placeholder="Поиск по инв. номеру, модели, серийному номеру"><select v-model="typeFilter"><option value="">Все типы</option><option v-for="t in ['pc','laptop','smartphone','tablet']" :value="t">{{labels[t]}}</option></select></div><div class="table-wrap"><table><thead><tr><th>Инв. №</th><th>Тип</th><th>Техника</th><th>Назначение</th><th>Состояние</th><th>Выдана</th><th>Стоимость</th><th>Остаточная</th><th></th></tr></thead><tbody><tr v-for="x in filtered" :key="x.id"><td><b>{{x.inventory_number}}</b></td><td>{{labels[x.type]}}</td><td>{{x.manufacturer}} {{x.model}}<small>{{x.serial_number||'—'}}</small></td><td>{{labels[x.purpose]}}</td><td><UiBadge>{{labels[x.condition]}}</UiBadge></td><td>{{x.assignment ? `#${x.assignment.employee_id}` : 'Свободна'}}</td><td>{{money(x.purchase_cost)}}</td><td>{{money(x.depreciation?.residual)}}</td><td class="actions"><UiButton v-if="permissions.manage" kind="secondary" @click="openEditor(x)">Изменить</UiButton><UiButton v-if="permissions.operate&&!x.written_off_at&&!x.assignment" kind="secondary" @click="openAssign(x)">Выдать</UiButton><UiButton v-if="permissions.operate&&x.assignment" kind="secondary" @click="returnItem(x)">Вернуть</UiButton><UiButton v-if="permissions.operate&&!x.written_off_at&&!x.assignment" kind="secondary" @click="writeOff(x)">Списать</UiButton></td></tr><tr v-if="!filtered.length"><td colspan="9" class="empty">Нет данных</td></tr></tbody></table></div></UiPanel>
<UiPanel v-if="section==='assignments'" class="panel"><div class="table-wrap"><table><thead><tr><th>Техника</th><th>Сотрудник</th><th>Начало</th><th>План возврата</th><th>Возврат</th><th>Кто выдал</th></tr></thead><tbody><tr v-for="x in assignments" :key="x.id"><td>{{x.inventory_number}} · {{x.manufacturer}} {{x.model}}</td><td>#{{x.employee_id}}</td><td>{{x.starts_on}}</td><td>{{x.planned_ends_on||'Без срока'}}</td><td>{{x.returned_on||'Активна'}}</td><td>{{x.issued_by}}</td></tr></tbody></table></div></UiPanel>
<UiPanel v-if="section==='depreciation'" class="panel"><div class="table-wrap"><table><thead><tr><th>Инв. №</th><th>Техника</th><th>Первоначальная</th><th>В месяц</th><th>Месяцев</th><th>Амортизация</th><th>Остаточная</th></tr></thead><tbody><tr v-for="x in depreciation" :key="x.id"><td>{{x.inventory_number}}</td><td>{{x.manufacturer}} {{x.model}}</td><td>{{money(x.purchase_cost)}}</td><td>{{money(x.depreciation.monthly)}}</td><td>{{x.depreciation.months}}</td><td>{{money(x.depreciation.accumulated)}}</td><td><b>{{money(x.depreciation.residual)}}</b></td></tr></tbody></table></div></UiPanel>
<div v-if="editor.open" class="modal-backdrop" @click.self="resetEditor"><form class="modal" @submit.prevent="saveItem"><h2>{{editor.id?'Редактирование':'Новая техника'}}</h2><div class="grid"><label>Инв. номер<input v-model="editor.inventory_number" required></label><label>Тип<select v-model="editor.type"><option v-for="t in ['pc','laptop','smartphone','tablet']" :value="t">{{labels[t]}}</option></select></label><label>Изготовитель<input v-model="editor.manufacturer" required></label><label>Модель<input v-model="editor.model" required></label><label>Серийный номер<input v-model="editor.serial_number"></label><label>Назначение<select v-model="editor.purpose"><option v-for="p in ['development','management_qa','qa','management']" :value="p">{{labels[p]}}</option></select></label><label>Состояние<select v-model="editor.condition"><option v-for="c in ['ok','damaged','needs_repair']" :value="c">{{labels[c]}}</option></select></label><label>Дата покупки<input v-model="editor.purchased_on" type="date"></label><label>Стоимость<input v-model="editor.purchase_cost" type="number" min="0" step="0.01"></label><label>Срок, мес.<input v-model="editor.useful_life_months" type="number" min="1"></label><label>Процессор<input v-model="editor.cpu"></label><label>ОЗУ<input v-model="editor.ram"></label><label>HDD/SSD<input v-model="editor.storage"></label><label>Видеокарта<input v-model="editor.gpu"></label><label>ОС<input v-model="editor.os"></label><label>Версия ОС<input v-model="editor.os_version"></label><label v-if="editor.type==='smartphone'||editor.type==='tablet'">IMEI<input v-model="editor.imei"></label><label class="wide">Комментарий<textarea v-model="editor.comment"></textarea></label></div><div class="modal-actions"><UiButton kind="secondary" type="button" @click="resetEditor">Отмена</UiButton><UiButton type="submit">Сохранить</UiButton></div></form></div>
<div v-if="assignment.open" class="modal-backdrop" @click.self="assignment.open=false"><form class="modal narrow" @submit.prevent="assignItem"><h2>Выдать {{assignment.item.inventory_number}}</h2><label>ID сотрудника<input v-model="assignment.employee_id" type="number" min="1" required></label><label>Дата выдачи<input v-model="assignment.starts_on" type="date" required></label><label>Плановый возврат<input v-model="assignment.planned_ends_on" type="date"></label><label>Комментарий<textarea v-model="assignment.issue_comment"></textarea></label><div class="modal-actions"><UiButton kind="secondary" type="button" @click="assignment.open=false">Отмена</UiButton><UiButton type="submit">Выдать</UiButton></div></form></div>
</main></UiAppShell>
</template>
