#!/usr/bin/env python3
"""Single service registry, content-addressed images and selective deployment plans.

No third-party Python dependencies; Docker Compose owns YAML interpretation.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import tempfile
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = "infra/ci/services.json"
BUILD_INPUTS = [".github/actions/build-service/", "scripts/ci/image_check.py", ".dockerignore"]


def run(*args, **kwargs):
    return subprocess.check_output(args, cwd=ROOT, text=True, **kwargs).strip()


def registry():
    data = json.loads((ROOT / REGISTRY).read_text())
    assert data["version"] == 1, "Unsupported registry version"
    for key in ("id", "service", "image", "tag_env"):
        values = [c[key] for c in data["components"]]
        assert len(values) == len(set(values)), f"Duplicate {key} in registry"
    for name in data.get("ephemeral_services", []):
        assert re.fullmatch(r"[a-z0-9][a-z0-9-]*", name), f"Invalid ephemeral service: {name}"
    for c in data["components"]:
        assert c["kind"] in ("frontend", "backend")
        assert re.fullmatch(r"[a-z0-9][a-z0-9-]*", c["id"])
        assert re.fullmatch(r"[A-Z][A-Z0-9_]*", c["tag_env"])
        assert c["paths"], f"Missing build paths: {c['id']}"
        assert c.get("health_path") if c["kind"] == "backend" else c.get("page_path"), f"Register smoke URL: {c['id']}"
    return data


def image_overlay(data):
    lines = ["# Generated by scripts/ci/service_plan.py images. Edit infra/ci/services.json.", "services:"]
    for c in data["components"]:
        for service in [c["service"], *c.get("aliases", [])]:
            lines += [f"  {service}:", f"    image: ghcr.io/gerlingerstanislav-creator/{c['image']}:${{{c['tag_env']}:-local}}"]
    return "\n".join(lines) + "\n"


def compose_command(data, env_file=".env.example"):
    docker = ["docker", "compose"] if subprocess.call(["sh", "-c", "docker compose version >/dev/null 2>&1"]) == 0 else ["docker-compose"]
    args = [*docker, "--project-name", "irlix-services", "--project-directory", str(ROOT)]
    for f in data["compose_files"]:
        args += ["-f", f]
    return [*args, "--env-file", env_file]


def compose_config(data, ref=None):
    # Always normalize paths against the same checkout, including old snapshots.
    env = os.environ.copy()
    for c in data["components"]:
        env.pop(c["tag_env"], None)
    with tempfile.TemporaryDirectory() as directory:
        args = ["docker", "compose", "--project-name", "irlix-services", "--project-directory", str(ROOT)]
        if ref:
            files = {}
            for f in [*data["compose_files"], ".env.example"]:
                result = subprocess.run(["git", "show", f"{ref}:{f}"], cwd=ROOT, text=True, capture_output=True)
                if result.returncode == 0:
                    target = Path(directory) / f
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text(result.stdout)
                    files[f] = str(target)
            if "docker-compose.yml" not in files:
                return {"services": {}}
            for f in data["compose_files"]:
                if f in files:
                    args += ["-f", files[f]]
            args += ["--env-file", files[".env.example"]]
        else:
            for f in data["compose_files"]:
                args += ["-f", f]
            args += ["--env-file", ".env.example"]
        return json.loads(run(*args, "config", "--format", "json", env=env))


def validate(data, config):
    services = config["services"]
    covered = set()
    for c in data["components"]:
        for name in [c["service"], *c.get("aliases", [])]:
            assert name not in covered, f"Compose service registered twice: {name}"
            covered.add(name)
            spec = services.get(name, {})
            assert spec.get("build"), f"Missing Compose build: {name}"
            assert spec.get("image", "").startswith(f"ghcr.io/gerlingerstanislav-creator/{c['image']}:")
            assert spec["build"] == services[c["service"]]["build"], f"Worker uses different build: {name}"
        build = services[c["service"]]["build"]
        dockerfile = Path(build["context"]) / build.get("dockerfile", "Dockerfile")
        path = dockerfile.relative_to(ROOT).as_posix()
        assert any(path.startswith(p) for p in c["paths"]), f"Dockerfile not covered by build paths: {path}"
    unknown = {name for name, spec in services.items() if spec.get("build")} - covered
    assert not unknown, f"Register new build services in {REGISTRY}: {sorted(unknown)}"
    ephemeral = set(data.get("ephemeral_services", []))
    assert ephemeral <= set(services), f"Unknown ephemeral services: {sorted(ephemeral - set(services))}"
    # A new deployable directory must not silently bypass CI by omitting Compose/registry.
    registered_paths = [p for c in data["components"] for p in c["paths"]]
    for parent in ("apps", "services"):
        for file in (ROOT / parent).glob("*/Dockerfile"):
            path = file.relative_to(ROOT).as_posix()
            assert any(path.startswith(p) for p in registered_paths), f"Unregistered Dockerfile: {path}"
    assert (ROOT / "docker-compose.images.yml").read_text() == image_overlay(data), "Regenerate docker-compose.images.yml"


def tracked_inputs(ref, paths):
    listing = run("git", "ls-tree", "-r", ref, "--", *paths)
    return "\n".join(line for line in listing.splitlines() if not line.endswith(".md"))


def fingerprint(component, spec, ref="HEAD"):
    build = dict(spec["build"])
    build["context"] = str(Path(build["context"]).relative_to(ROOT))
    payload = [component, build, tracked_inputs(ref, [*component["paths"], *BUILD_INPUTS])]
    return "src-" + hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()[:40]


def make_plan(data, current, previous, changed, ref="HEAD", base=None, full=False, hash_image=fingerprint, old_registry=None):
    """Compare build inputs separately from runtime configuration and checks."""
    images, runtime, migrations, checks, reasons = [], set(), [], set(), {}
    old_services = previous.get("services", {})
    new_services = current["services"]
    ephemeral = set(data.get("ephemeral_services", []))
    old_components = {c["id"]: c for c in (old_registry or data)["components"]}
    for c in data["components"]:
        name = c["service"]
        spec = new_services[name]
        selected = full or name not in old_services or old_components.get(c["id"]) != c
        matching = [p for p in changed if not p.endswith(".md") and any(p.startswith(root) for root in [*c["paths"], *BUILD_INPUTS])]
        old_build = old_services.get(name, {}).get("build")
        if matching or old_build != spec["build"]:
            selected = True
        members = [name, *c.get("aliases", [])]
        affected = selected or any(new_services.get(s) != old_services.get(s) for s in members)
        if selected:
            tag = hash_image(c, spec, ref)
            build = spec["build"]
            images.append({**c, "tag": tag, "image_ref": f"ghcr.io/gerlingerstanislav-creator/{c['image']}:{tag}",
                           "context": str(Path(build["context"]).relative_to(ROOT)), "dockerfile": build.get("dockerfile", "Dockerfile"),
                           "build_args": build.get("args", {}), "target": build.get("target", "")})
            reasons[c["id"]] = matching or ["explicit full build" if full else "new service or changed build definition"]
        if affected:
            runtime.update(members)
            checks.update(c.get("verify", []))
            if c.get("migrate"):
                migrations.append(name)
    for name, spec in new_services.items():
        if name in ephemeral:
            continue
        if not spec.get("build") and (full or spec != old_services.get(name)):
            runtime.add(name)
    auth = full or "keycloak" in runtime or any(p.startswith("infra/keycloak/") for p in changed)
    if auth:
        runtime.add("keycloak")
    # A bind-mounted bootstrap/theme change affects its owning infrastructure service.
    if any(p.startswith("infra/postgres/") for p in changed):
        runtime.add("postgres")
    routing = full or "infra/nginx/irlix-services.conf" in changed
    cv_check = full or bool({"cv-converter", "cv-llm"} & runtime)
    if {"recruitment", "recruitment-web"} & runtime:
        checks.add("scripts/verify-recruitment.sh")
    checks.update(p for p in changed if p.startswith("scripts/verify-") and p.endswith(".sh"))
    schema = full or bool(migrations) or any(p.startswith("infra/postgres/") for p in changed)
    deployment_tools = any(p in ("scripts/deploy-from-ghcr.sh", "scripts/ci/service_plan.py", "scripts/ci/verify_plan.py", REGISTRY) for p in changed)
    return {"version": 1, "commit": ref, "base": base, "full": full, "images": images,
            "services": sorted(runtime), "migrations": migrations, "schema": schema,
            "auth": auth, "routing": routing, "cv_check": cv_check, "verify": sorted(checks), "reasons": reasons,
            "deploy": bool(runtime or routing or checks or auth or schema or deployment_tools)}


def github_json(url):
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {os.environ['GH_TOKEN']}", "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as response:
        return json.load(response)


def is_ancestor(sha):
    return subprocess.call(["git", "merge-base", "--is-ancestor", sha, "HEAD"], cwd=ROOT) == 0


def previous_success():
    branch = os.environ.get("GITHUB_REF_NAME", "development")
    params = {"branch": branch, "event": "push", "per_page": 100}
    # Development is only a verification baseline. Main is different: its baseline must describe
    # what is actually deployed. A release whose deploy succeeded but whose later smoke failed has
    # already advanced the server and must not cause unrelated components to be pulled/up'ed again.
    if branch != "main":
        params["status"] = "success"
    query = urllib.parse.urlencode(params)
    repo = os.environ["GITHUB_REPOSITORY"]
    url = f"https://api.github.com/repos/{repo}/actions/runs?{query}"
    runs = github_json(url)["workflow_runs"]
    had_successful_ancestor = False
    for r in runs:
        if r.get("path", ".github/workflows/ci.yml").split("@", 1)[0] != ".github/workflows/ci.yml":
            continue
        sha = r["head_sha"]
        if sha == os.environ["GITHUB_SHA"] or not is_ancestor(sha):
            continue
        had_successful_ancestor = had_successful_ancestor or r.get("conclusion") == "success"
        if branch == "main":
            jobs = github_json(r["jobs_url"]).get("jobs", [])
            deploy = next((j for j in jobs if j.get("name") == "Pull and deploy affected components"), None)
            if not deploy or deploy.get("conclusion") != "success":
                continue
        return sha
    if branch != "main":
        return run("git", "merge-base", "HEAD", "origin/main")
    if had_successful_ancestor:
        raise RuntimeError("Successful main CI history exists, but its deployed baseline cannot be resolved. Refusing an implicit full deployment.")
    return None  # No successful deploy: intentionally bootstrap the whole stand.


def outputs(plan):
    matrix = {"include": plan["images"] or [{"id": "not-required", "skip": True}]}
    values = {"matrix": json.dumps(matrix, separators=(",", ":")), "deploy": str(plan["deploy"]).lower(), "auth": str(plan["auth"]).lower()}
    if os.environ.get("GITHUB_OUTPUT"):
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            for key, value in values.items():
                f.write(f"{key}={value}\n")
    print(json.dumps({"base": plan["base"], "images": [c["id"] for c in plan["images"]], "services": plan["services"], "reasons": plan["reasons"]}, ensure_ascii=False, indent=2))
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as f:
            f.write("### Selected components\n\n")
            for c in plan["images"]:
                f.write(f"- `{c['id']}`: {', '.join(plan['reasons'][c['id']])}\n")
            f.write(f"\nRuntime updates: {', '.join(plan['services']) or 'none'}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["plan", "validate", "images", "compose-args", "deploy-env", "deploy-controls"])
    parser.add_argument("--base")
    parser.add_argument("--full", action="store_true")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--env-file", default=".env.example")
    parser.add_argument("--plan-file", default=".ci/deploy-plan.json")
    args = parser.parse_args()
    data = registry()
    if args.command == "images":
        if args.write:
            (ROOT / "docker-compose.images.yml").write_text(image_overlay(data))
        else:
            assert (ROOT / "docker-compose.images.yml").read_text() == image_overlay(data), "Regenerate image overlay"
        return
    if args.command == "compose-args":
        print(shlex.join(compose_command(data, args.env_file)))
        return
    if args.command in ("deploy-env", "deploy-controls"):
        plan = json.loads((ROOT / args.plan_file).read_text())
        assert plan["version"] == 1
        if os.environ.get("GITHUB_SHA"):
            assert plan["commit"] == os.environ["GITHUB_SHA"], "Release archive/plan commit mismatch"
        known = {c["id"]: c for c in data["components"]}
        for c in plan["images"]:
            assert c["tag_env"] == known[c["id"]]["tag_env"]
            assert re.fullmatch(r"src-[a-f0-9]{40}", c["tag"])
            if args.command == "deploy-env":
                print(f"{c['tag_env']}={c['tag']}")
        if args.command == "deploy-controls":
            for field in ("services", "migrations"):
                assert all(re.fullmatch(r"[a-z0-9][a-z0-9-]*", s) for s in plan[field])
            values = {k.upper(): str(plan[k]).lower() for k in ("full", "auth", "routing", "schema", "cv_check")}
            values.update(DEPLOY_SERVICES=" ".join(plan["services"]), MIGRATE_SERVICES=" ".join(plan["migrations"]))
            for key, value in values.items():
                print(f"{key}={shlex.quote(value)}")
        return
    current = compose_config(data)
    validate(data, current)
    if args.command == "validate":
        print("Registry and complete Compose stack are valid")
        return
    base = args.base or previous_success()
    previous = compose_config(data, base) if base else {"services": {}}
    old_registry = None
    if base:
        result = subprocess.run(["git", "show", f"{base}:{REGISTRY}"], cwd=ROOT, text=True, capture_output=True)
        if result.returncode == 0:
            old_registry = json.loads(result.stdout)
    changed = run("git", "diff", "--name-only", base, "HEAD").splitlines() if base else []
    plan = make_plan(data, current, previous, changed, ref=run("git", "rev-parse", "HEAD"), base=base, full=args.full or base is None, old_registry=old_registry)
    path = ROOT / args.plan_file
    path.parent.mkdir(exist_ok=True)
    path.write_text(json.dumps(plan, indent=2) + "\n")
    outputs(plan)


if __name__ == "__main__":
    main()
