<script setup>
import { nextTick, ref } from 'vue';
const props=defineProps({label:String,value:String,editable:Boolean,busy:Boolean,maxlength:{default:5000}});
const emit=defineEmits(['save']);const expanded=ref(true),editing=ref(false),draft=ref(''),input=ref(null);
async function start(){draft.value=props.value||'';expanded.value=true;editing.value=true;await nextTick();input.value?.focus();}
function save(){emit('save',draft.value,success=>{if(success)editing.value=false;});}
</script>
<template><fieldset class="description-block"><legend><button type="button" class="description-toggle" :aria-label="(expanded?'Скрыть ':'Показать ')+label" :aria-expanded="expanded" @click="expanded=!expanded">{{expanded?'−':'+'}}</button><span>{{label}}</span><template v-if="editing"><button type="button" class="description-confirm" :disabled="busy" :aria-label="'Сохранить '+label" @click="save">✓</button><button type="button" class="description-cancel" :disabled="busy" :aria-label="'Отменить редактирование '+label" @click="editing=false">×</button></template><button v-else-if="editable" type="button" class="description-pencil" :disabled="busy" :aria-label="'Редактировать '+label" @click="start">✎</button></legend><template v-if="expanded"><form v-if="editing" @submit.prevent="save"><textarea ref="input" v-model="draft" rows="6" :maxlength="maxlength" :aria-label="label"/></form><p v-else>{{value||'Описание не заполнено'}}</p></template></fieldset></template>
<style scoped>
.description-block{min-width:0;margin:0;padding:12px 16px 16px;border:1px solid #d9dde1;border-radius:5px}.description-block legend{padding:0 10px;display:flex;align-items:center;gap:6px;font-size:var(--irlix-font-size-body);font-weight:600}.description-block p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.5}.description-block button.description-toggle,.description-pencil,.description-confirm,.description-cancel{border:0;background:transparent;padding:0 2px;font:inherit;color:#778897;cursor:pointer}.description-block button.description-toggle{width:18px;color:var(--irlix-color-primary,#078d6c);font-size:var(--irlix-font-size-section-title);font-weight:600;line-height:1}.description-block button.description-toggle:hover{color:#056d55}.description-pencil{color:#5989c7}.description-confirm{color:#078d6c!important}.description-cancel{color:#7c858e!important}.description-block form{display:block}.description-block textarea{width:100%;min-height:140px;padding:9px;border:1px solid var(--irlix-control-border,#d8dde4);border-radius:var(--irlix-control-radius,8px);outline:0;background:var(--irlix-color-surface);color:var(--irlix-control-text,#4f5967);font:inherit;resize:vertical}.description-block textarea:focus{border-color:var(--irlix-color-primary,#12b890);box-shadow:0 0 0 2px rgba(18,184,144,.1)}
</style>
