<?php

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Validator;

function equipmentRoles(Request $request): array { return $request->attributes->get('identity')['realm_roles'] ?? []; }
function equipmentActor(Request $request): string { $i=$request->attributes->get('identity') ?? []; return (string)($i['preferred_username'] ?? $i['email'] ?? $i['sub'] ?? 'unknown'); }
function equipmentAllowedRoles(string $env, array $defaults): array { return array_values(array_filter(array_map('trim', explode(',', (string) env($env, implode(',', $defaults)))))); }
function equipmentCanView(Request $request): bool { $r=equipmentRoles($request); return in_array('platform-admin',$r,true) || count(array_intersect($r, array_merge(equipmentAllowedRoles('EQUIPMENT_ADMIN_ROLES',['system-admin','sysadmin']), equipmentAllowedRoles('EQUIPMENT_ACCOUNTING_ROLES',['accounting','accountant']))))>0; }
function equipmentCanManage(Request $request): bool { return equipmentCanView($request); }
function equipmentCanOperate(Request $request): bool { $r=equipmentRoles($request); return in_array('platform-admin',$r,true) || count(array_intersect($r, equipmentAllowedRoles('EQUIPMENT_ADMIN_ROLES',['system-admin','sysadmin'])))>0; }
function equipmentGuard(bool $allowed) { return $allowed ? null : response()->json(['message'=>'Forbidden'],403); }
function equipmentToken(Request $request): ?string { return $request->bearerToken() ?: $request->header('X-Irlix-Access-Token'); }
function equipmentEmployeesRequest(Request $request) { return Http::withToken((string) equipmentToken($request))->acceptJson()->timeout(5); }
function equipmentDefaultUsefulLife(): array { return ['pc'=>48,'laptop'=>36,'smartphone'=>36,'tablet'=>36]; }
function equipmentSettings(): array {
    $defaults=equipmentDefaultUsefulLife();
    if (!DB::getSchemaBuilder()->hasTable('equipment_settings')) return $defaults;
    $rows=DB::table('equipment_settings')->pluck('useful_life_months','equipment_type')->all();
    foreach($defaults as $type=>$months) $defaults[$type]=(int)($rows[$type]??$months);
    return $defaults;
}
function equipmentDepreciation(object|array $item, ?Carbon $asOf=null): array {
    $v=(array)$item; $cost=(float)($v['purchase_cost'] ?? 0); $life=(int)($v['useful_life_months'] ?? 0); $date=$v['purchased_on'] ?? null;
    if (!$date || $cost<=0 || $life<=0) return ['monthly'=>0,'months'=>0,'accumulated'=>0,'residual'=>$cost];
    $from=Carbon::parse($date)->startOfDay(); $until=$asOf ?: (!empty($v['written_off_at']) ? Carbon::parse($v['written_off_at']) : now());
    $months=max(0,min($life,(int)floor($from->diffInMonths($until->copy()->startOfDay())))); $monthly=$cost/$life; $acc=min($cost,$monthly*$months);
    return ['monthly'=>round($monthly,2),'months'=>$months,'accumulated'=>round($acc,2),'residual'=>round(max(0,$cost-$acc),2)];
}
function equipmentDamageSummary(int $itemId,float $residual): array {
    $row=DB::table('equipment_damages')->where('equipment_item_id',$itemId)->selectRaw('COALESCE(SUM(repair_cost),0) AS repair_cost, COALESCE(SUM(value_loss),0) AS value_loss, COUNT(*) AS damage_count')->first();
    $repair=(float)($row->repair_cost??0); $loss=(float)($row->value_loss??0);
    return ['repair_cost'=>round($repair,2),'value_loss'=>round($loss,2),'damage_count'=>(int)($row->damage_count??0),'current_value'=>round(max(0,$residual-$loss),2)];
}
function equipmentDecorate($row): array {
    $item=(array)$row; $active=DB::table('equipment_assignments')->where('equipment_item_id',$item['id'])->whereNull('returned_on')->first();
    $item['assignment']=$active; $item['is_assigned']=$active!==null; $item['depreciation']=equipmentDepreciation($item);
    $item['damage_accounting']=equipmentDamageSummary((int)$item['id'],(float)$item['depreciation']['residual']); return $item;
}
function equipmentAudit(int $id,string $event,Request $request,array $payload=[]): void { DB::table('equipment_audit_log')->insert(['equipment_item_id'=>$id,'event'=>$event,'actor'=>equipmentActor($request),'payload'=>json_encode($payload,JSON_UNESCAPED_UNICODE),'created_at'=>now(),'updated_at'=>now()]); }
function equipmentEmployeeError(Request $r,int $employeeId,bool $mustBeEmployed=false) {
    $base=rtrim((string)env('EMPLOYEES_URL','http://employees:8000/api'),'/');
    try{$check=equipmentEmployeesRequest($r)->get("{$base}/employees/{$employeeId}");}catch(\Throwable){return response()->json(['message'=>'Employees service unavailable'],503);}
    if(!$check->successful())return response()->json(['message'=>'Employee not found or Employees unavailable'],422); $employee=$check->json('data.employee');
    if(!is_array($employee))return response()->json(['message'=>'Employee not found'],422);
    if($mustBeEmployed&&($employee['employment_status']??null)!=='Трудоустроен')return response()->json(['message'=>'Equipment can only be assigned to an employed employee'],422); return null;
}
function equipmentAssignmentOverlap(int $itemId,string $startsOn,?string $returnedOn=null,?int $excludeId=null): bool {
    $end=$returnedOn?:'9999-12-31'; $q=DB::table('equipment_assignments')->where('equipment_item_id',$itemId)->whereDate('starts_on','<=',$end)->where(fn($x)=>$x->whereNull('returned_on')->orWhereDate('returned_on','>=',$startsOn));
    if($excludeId)$q->where('id','!=',$excludeId); return $q->exists();
}

Route::get('/health', fn()=>response()->json(['service'=>'equipment','status'=>'ok','database'=>DB::select('select 1')?'ok':'error']));
Route::get('/permissions', function(Request $r){ return response()->json(['data'=>['view'=>equipmentCanView($r),'manage'=>equipmentCanManage($r),'operate'=>equipmentCanOperate($r)]]); });
Route::get('/settings', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; return response()->json(['data'=>equipmentSettings()]); });
Route::patch('/settings', function(Request $r){
    if($g=equipmentGuard(equipmentCanManage($r)))return $g;
    $v=Validator::make($r->all(),['pc'=>'required|integer|min:1|max:600','laptop'=>'required|integer|min:1|max:600','smartphone'=>'required|integer|min:1|max:600','tablet'=>'required|integer|min:1|max:600'])->validate();
    DB::transaction(function()use($v){ foreach($v as $type=>$months) DB::table('equipment_settings')->updateOrInsert(['equipment_type'=>$type],['useful_life_months'=>$months,'updated_at'=>now(),'created_at'=>now()]); });
    return response()->json(['data'=>equipmentSettings()]);
});
Route::get('/employees-directory', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $base=rtrim((string)env('EMPLOYEES_URL','http://employees:8000/api'),'/'); try{$response=equipmentEmployeesRequest($r)->get("{$base}/employees",['employment_status'=>'Трудоустроен']);}catch(\Throwable){return response()->json(['message'=>'Employees service unavailable'],503);} if(!$response->successful())return response()->json(['message'=>'Employees directory unavailable'],502); $rows=$response->json('data'); if(!is_array($rows))$rows=[]; $data=array_values(array_map(fn($e)=>['id'=>(int)($e['id']??0),'full_name'=>$e['full_name']??'','position'=>$e['position']??null,'department_name'=>$e['department_name']??null],array_filter($rows,fn($e)=>isset($e['id'])))); return response()->json(['data'=>$data]); });
Route::get('/items', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $q=DB::table('equipment_items'); if($r->boolean('written_off'))$q->whereNotNull('written_off_at'); else if(!$r->boolean('all'))$q->whereNull('written_off_at'); if($r->filled('type'))$q->where('type',$r->string('type')); if($r->filled('search')){$s='%'.$r->string('search').'%';$q->where(fn($x)=>$x->where('inventory_number','ilike',$s)->orWhere('manufacturer','ilike',$s)->orWhere('model','ilike',$s)->orWhere('serial_number','ilike',$s));} return response()->json(['data'=>$q->orderBy('inventory_number')->get()->map(fn($x)=>equipmentDecorate($x))]); });
Route::get('/items/{id}', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); $data=equipmentDecorate($item); $data['assignments']=DB::table('equipment_assignments')->where('equipment_item_id',$id)->orderByDesc('starts_on')->orderByDesc('id')->get(); $data['damages']=DB::table('equipment_damages')->where('equipment_item_id',$id)->orderByDesc('occurred_on')->orderByDesc('id')->get(); $data['write_off']=DB::table('equipment_write_offs')->where('equipment_item_id',$id)->first(); $data['history']=DB::table('equipment_audit_log')->where('equipment_item_id',$id)->orderByDesc('id')->get(); return response()->json(['data'=>$data]); });
Route::post('/items', function(Request $r){
    if($g=equipmentGuard(equipmentCanManage($r)))return $g;
    $v=Validator::make($r->all(),['inventory_number'=>'required|string|max:100|unique:equipment_items,inventory_number','type'=>'required|in:pc,laptop,smartphone,tablet','manufacturer'=>'required|string|max:160','model'=>'required|string|max:160','serial_number'=>'nullable|string|max:200','purpose'=>'required|in:development,management_qa,qa,management','condition'=>'required|in:ok,damaged,needs_repair','comment'=>'nullable|string','purchased_on'=>'nullable|date','purchase_cost'=>'nullable|numeric|min:0','useful_life_months'=>'nullable|integer|min:1|max:600','cpu'=>'nullable|string|max:200','ram'=>'nullable|string|max:100','storage'=>'nullable|string|max:200','gpu'=>'nullable|string|max:200','os'=>'nullable|string|max:100','os_version'=>'nullable|string|max:100','imei'=>'nullable|string|max:32'])->validate();
    if(empty($v['useful_life_months'])) $v['useful_life_months']=equipmentSettings()[$v['type']];
    $id=DB::table('equipment_items')->insertGetId(array_merge($v,['created_at'=>now(),'updated_at'=>now()])); equipmentAudit($id,'created',$r,$v); return response()->json(['data'=>equipmentDecorate(DB::table('equipment_items')->find($id))],201);
});
Route::patch('/items/{id}', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanManage($r)))return $g; if(!DB::table('equipment_items')->find($id))return response()->json(['message'=>'Not found'],404); $v=Validator::make($r->all(),['inventory_number'=>'sometimes|required|string|max:100|unique:equipment_items,inventory_number,'.$id,'type'=>'sometimes|required|in:pc,laptop,smartphone,tablet','manufacturer'=>'sometimes|required|string|max:160','model'=>'sometimes|required|string|max:160','serial_number'=>'nullable|string|max:200','purpose'=>'sometimes|required|in:development,management_qa,qa,management','condition'=>'sometimes|required|in:ok,damaged,needs_repair','comment'=>'nullable|string','purchased_on'=>'nullable|date','purchase_cost'=>'nullable|numeric|min:0','useful_life_months'=>'nullable|integer|min:1|max:600','cpu'=>'nullable|string|max:200','ram'=>'nullable|string|max:100','storage'=>'nullable|string|max:200','gpu'=>'nullable|string|max:200','os'=>'nullable|string|max:100','os_version'=>'nullable|string|max:100','imei'=>'nullable|string|max:32'])->validate(); DB::table('equipment_items')->where('id',$id)->update(array_merge($v,['updated_at'=>now()])); equipmentAudit($id,'updated',$r,$v); return response()->json(['data'=>equipmentDecorate(DB::table('equipment_items')->find($id))]); });

Route::post('/items/{id}/assign', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); if($item->written_off_at)return response()->json(['message'=>'Written-off equipment cannot be assigned'],409); $v=Validator::make($r->all(),['employee_id'=>'required|integer|min:1','starts_on'=>'required|date','issue_comment'=>'nullable|string'])->validate(); if(equipmentAssignmentOverlap($id,$v['starts_on']))return response()->json(['message'=>'Assignment period overlaps existing history'],409); if($e=equipmentEmployeeError($r,(int)$v['employee_id'],true))return $e; $aid=DB::table('equipment_assignments')->insertGetId(array_merge($v,['equipment_item_id'=>$id,'issued_by'=>equipmentActor($r),'created_at'=>now(),'updated_at'=>now()])); equipmentAudit($id,'assigned',$r,['assignment_id'=>$aid,'employee_id'=>$v['employee_id'],'starts_on'=>$v['starts_on']]); return response()->json(['data'=>DB::table('equipment_assignments')->find($aid)],201); });
Route::post('/items/{id}/return', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $a=DB::table('equipment_assignments')->where('equipment_item_id',$id)->whereNull('returned_on')->first(); if(!$a)return response()->json(['message'=>'No active assignment'],409); $v=Validator::make($r->all(),['returned_on'=>'required|date|after_or_equal:'.$a->starts_on,'return_comment'=>'nullable|string'])->validate(); DB::table('equipment_assignments')->where('id',$a->id)->update(['returned_on'=>$v['returned_on'],'returned_by'=>equipmentActor($r),'return_comment'=>$v['return_comment']??null,'updated_at'=>now()]); equipmentAudit($id,'returned',$r,['assignment_id'=>$a->id,'returned_on'=>$v['returned_on'],'return_comment'=>$v['return_comment']??null]); return response()->json(['data'=>DB::table('equipment_assignments')->find($a->id)]); });
Route::patch('/assignments/{assignmentId}', function(Request $r,int $assignmentId){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $a=DB::table('equipment_assignments')->find($assignmentId); if(!$a)return response()->json(['message'=>'Assignment not found'],404); if(!$a->returned_on)return response()->json(['message'=>'Active assignment must be returned before editing history'],409); $v=Validator::make($r->all(),['employee_id'=>'required|integer|min:1','starts_on'=>'required|date','returned_on'=>'required|date|after_or_equal:starts_on','issue_comment'=>'nullable|string','return_comment'=>'nullable|string'])->validate(); if(equipmentAssignmentOverlap((int)$a->equipment_item_id,$v['starts_on'],$v['returned_on'],$assignmentId))return response()->json(['message'=>'Assignment period overlaps existing history'],409); if($e=equipmentEmployeeError($r,(int)$v['employee_id']))return $e; DB::table('equipment_assignments')->where('id',$assignmentId)->update(array_merge($v,['updated_at'=>now()])); equipmentAudit((int)$a->equipment_item_id,'assignment_updated',$r,['assignment_id'=>$assignmentId]+$v); return response()->json(['data'=>DB::table('equipment_assignments')->find($assignmentId)]); });
Route::delete('/assignments/{assignmentId}', function(Request $r,int $assignmentId){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $a=DB::table('equipment_assignments')->find($assignmentId); if(!$a)return response()->json(['message'=>'Assignment not found'],404); if(!$a->returned_on)return response()->json(['message'=>'Active assignment must be returned before deletion'],409); DB::table('equipment_assignments')->where('id',$assignmentId)->delete(); equipmentAudit((int)$a->equipment_item_id,'assignment_deleted',$r,['assignment_id'=>$assignmentId]); return response()->json(['data'=>true]); });

Route::post('/items/{id}/damages', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanManage($r)))return $g; if(!DB::table('equipment_items')->find($id))return response()->json(['message'=>'Not found'],404); $v=Validator::make($r->all(),['occurred_on'=>'required|date','description'=>'required|string','repair_cost'=>'nullable|numeric|min:0','repaired_on'=>'nullable|date|after_or_equal:occurred_on','value_loss'=>'nullable|numeric|min:0'])->validate(); $did=DB::table('equipment_damages')->insertGetId(array_merge($v,['repair_cost'=>$v['repair_cost']??0,'value_loss'=>$v['value_loss']??0,'equipment_item_id'=>$id,'actor'=>equipmentActor($r),'created_at'=>now(),'updated_at'=>now()])); equipmentAudit($id,'damage_created',$r,['damage_id'=>$did]+$v); return response()->json(['data'=>DB::table('equipment_damages')->find($did)],201); });
Route::patch('/damages/{damageId}', function(Request $r,int $damageId){ if($g=equipmentGuard(equipmentCanManage($r)))return $g; $d=DB::table('equipment_damages')->find($damageId); if(!$d)return response()->json(['message'=>'Damage not found'],404); $v=Validator::make($r->all(),['occurred_on'=>'required|date','description'=>'required|string','repair_cost'=>'nullable|numeric|min:0','repaired_on'=>'nullable|date|after_or_equal:occurred_on','value_loss'=>'nullable|numeric|min:0'])->validate(); DB::table('equipment_damages')->where('id',$damageId)->update(array_merge($v,['repair_cost'=>$v['repair_cost']??0,'value_loss'=>$v['value_loss']??0,'updated_at'=>now()])); equipmentAudit((int)$d->equipment_item_id,'damage_updated',$r,['damage_id'=>$damageId]+$v); return response()->json(['data'=>DB::table('equipment_damages')->find($damageId)]); });
Route::delete('/damages/{damageId}', function(Request $r,int $damageId){ if($g=equipmentGuard(equipmentCanManage($r)))return $g; $d=DB::table('equipment_damages')->find($damageId); if(!$d)return response()->json(['message'=>'Damage not found'],404); DB::table('equipment_damages')->where('id',$damageId)->delete(); equipmentAudit((int)$d->equipment_item_id,'damage_deleted',$r,['damage_id'=>$damageId]); return response()->json(['data'=>true]); });

Route::post('/items/{id}/write-off', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); if($item->written_off_at)return response()->json(['message'=>'Already written off'],409); if(DB::table('equipment_assignments')->where('equipment_item_id',$id)->whereNull('returned_on')->exists())return response()->json(['message'=>'Return equipment before write-off'],409); $v=Validator::make($r->all(),['written_off_on'=>'required|date','reason'=>'required|string|max:500','comment'=>'nullable|string'])->validate(); $dep=equipmentDepreciation($item,Carbon::parse($v['written_off_on'])); DB::transaction(function()use($id,$v,$dep,$r){DB::table('equipment_items')->where('id',$id)->update(['written_off_at'=>$v['written_off_on'],'updated_at'=>now()]); DB::table('equipment_write_offs')->insert(['equipment_item_id'=>$id,'written_off_on'=>$v['written_off_on'],'reason'=>$v['reason'],'comment'=>$v['comment']??null,'actor'=>equipmentActor($r),'residual_value'=>$dep['residual'],'created_at'=>now(),'updated_at'=>now()]); equipmentAudit($id,'written_off',$r,['written_off_on'=>$v['written_off_on'],'reason'=>$v['reason'],'residual_value'=>$dep['residual']]);}); return response()->json(['data'=>equipmentDecorate(DB::table('equipment_items')->find($id))]); });
Route::get('/assignments', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $rows=DB::table('equipment_assignments as a')->join('equipment_items as i','i.id','=','a.equipment_item_id')->select('a.*','i.inventory_number','i.manufacturer','i.model','i.type')->orderByDesc('a.starts_on')->get(); return response()->json(['data'=>$rows]); });
$equipmentValuationResponse=function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; return response()->json(['data'=>DB::table('equipment_items')->orderBy('inventory_number')->get()->map(function($i){$x=equipmentDecorate($i);return ['id'=>$i->id,'inventory_number'=>$i->inventory_number,'manufacturer'=>$i->manufacturer,'model'=>$i->model,'purchase_cost'=>(float)($i->purchase_cost??0),'useful_life_months'=>(int)($i->useful_life_months??0),'written_off_at'=>$i->written_off_at,'depreciation'=>$x['depreciation'],'damage_accounting'=>$x['damage_accounting']];})]); };
Route::get('/valuation',$equipmentValuationResponse);
Route::get('/depreciation',$equipmentValuationResponse);
