<?php

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Validator;

function equipmentRoles(Request $request): array { return $request->attributes->get('identity')['realm_roles'] ?? []; }
function equipmentActor(Request $request): string { $i=$request->attributes->get('identity') ?? []; return (string)($i['preferred_username'] ?? $i['email'] ?? $i['sub'] ?? 'unknown'); }
function equipmentAllowedRoles(string $env, array $defaults): array { return array_values(array_filter(array_map('trim', explode(',', (string) env($env, implode(',', $defaults)))))); }
function equipmentCanView(Request $request): bool { $r=equipmentRoles($request); return in_array('platform-admin',$r,true) || count(array_intersect($r, array_merge(equipmentAllowedRoles('EQUIPMENT_ADMIN_ROLES',['system-admin','sysadmin']), equipmentAllowedRoles('EQUIPMENT_ACCOUNTING_ROLES',['accounting','accountant']))))>0; }
function equipmentCanManage(Request $request): bool { return equipmentCanView($request); }
function equipmentCanOperate(Request $request): bool { $r=equipmentRoles($request); return in_array('platform-admin',$r,true) || count(array_intersect($r, equipmentAllowedRoles('EQUIPMENT_ADMIN_ROLES',['system-admin','sysadmin'])))>0; }
function equipmentGuard(bool $allowed) { return $allowed ? null : response()->json(['message'=>'Forbidden'],403); }
function equipmentDepreciation(object|array $item, ?Carbon $asOf=null): array {
    $v=(array)$item; $cost=(float)($v['purchase_cost'] ?? 0); $life=(int)($v['useful_life_months'] ?? 0); $date=$v['purchased_on'] ?? null;
    if (!$date || $cost<=0 || $life<=0) return ['monthly'=>0,'months'=>0,'accumulated'=>0,'residual'=>$cost];
    $from=Carbon::parse($date)->startOfDay(); $until=$asOf ?: (!empty($v['written_off_at']) ? Carbon::parse($v['written_off_at']) : now());
    $months=max(0,min($life,$from->diffInMonths($until->copy()->startOfDay()))); $monthly=$cost/$life; $acc=min($cost,$monthly*$months);
    return ['monthly'=>round($monthly,2),'months'=>$months,'accumulated'=>round($acc,2),'residual'=>round(max(0,$cost-$acc),2)];
}
function equipmentDecorate($row): array { $item=(array)$row; $active=DB::table('equipment_assignments')->where('equipment_item_id',$item['id'])->whereNull('returned_on')->first(); $item['assignment']=$active; $item['is_assigned']=$active!==null; $item['depreciation']=equipmentDepreciation($item); return $item; }
function equipmentAudit(int $id,string $event,Request $request,array $payload=[]): void { DB::table('equipment_audit_log')->insert(['equipment_item_id'=>$id,'event'=>$event,'actor'=>equipmentActor($request),'payload'=>json_encode($payload,JSON_UNESCAPED_UNICODE),'created_at'=>now(),'updated_at'=>now()]); }

Route::get('/health', fn()=>response()->json(['service'=>'equipment','status'=>'ok','database'=>DB::select('select 1')?'ok':'error']));
Route::get('/permissions', function(Request $r){ return response()->json(['data'=>['view'=>equipmentCanView($r),'manage'=>equipmentCanManage($r),'operate'=>equipmentCanOperate($r)]]); });
Route::get('/items', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $q=DB::table('equipment_items'); if($r->boolean('written_off'))$q->whereNotNull('written_off_at'); else if(!$r->boolean('all'))$q->whereNull('written_off_at'); if($r->filled('type'))$q->where('type',$r->string('type')); if($r->filled('search')){ $s='%'.$r->string('search').'%'; $q->where(fn($x)=>$x->where('inventory_number','ilike',$s)->orWhere('manufacturer','ilike',$s)->orWhere('model','ilike',$s)->orWhere('serial_number','ilike',$s)); } return response()->json(['data'=>$q->orderBy('inventory_number')->get()->map(fn($x)=>equipmentDecorate($x))]); });
Route::get('/items/{id}', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); $data=equipmentDecorate($item); $data['assignments']=DB::table('equipment_assignments')->where('equipment_item_id',$id)->orderByDesc('starts_on')->get(); $data['write_off']=DB::table('equipment_write_offs')->where('equipment_item_id',$id)->first(); $data['history']=DB::table('equipment_audit_log')->where('equipment_item_id',$id)->orderByDesc('id')->get(); return response()->json(['data'=>$data]); });
Route::post('/items', function(Request $r){ if($g=equipmentGuard(equipmentCanManage($r)))return $g; $v=Validator::make($r->all(),['inventory_number'=>'required|string|max:100|unique:equipment_items,inventory_number','type'=>'required|in:pc,laptop,smartphone,tablet','manufacturer'=>'required|string|max:160','model'=>'required|string|max:160','serial_number'=>'nullable|string|max:200','purpose'=>'required|in:development,management_qa,qa,management','condition'=>'required|in:ok,damaged,needs_repair','comment'=>'nullable|string','purchased_on'=>'nullable|date','purchase_cost'=>'nullable|numeric|min:0','useful_life_months'=>'nullable|integer|min:1|max:600','cpu'=>'nullable|string|max:200','ram'=>'nullable|string|max:100','storage'=>'nullable|string|max:200','gpu'=>'nullable|string|max:200','os'=>'nullable|string|max:100','os_version'=>'nullable|string|max:100','imei'=>'nullable|string|max:32'])->validate(); $now=now(); $id=DB::table('equipment_items')->insertGetId(array_merge($v,['created_at'=>$now,'updated_at'=>$now])); equipmentAudit($id,'created',$r,$v); return response()->json(['data'=>equipmentDecorate(DB::table('equipment_items')->find($id))],201); });
Route::patch('/items/{id}', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanManage($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); $v=Validator::make($r->all(),['inventory_number'=>'sometimes|required|string|max:100|unique:equipment_items,inventory_number,'.$id,'type'=>'sometimes|required|in:pc,laptop,smartphone,tablet','manufacturer'=>'sometimes|required|string|max:160','model'=>'sometimes|required|string|max:160','serial_number'=>'nullable|string|max:200','purpose'=>'sometimes|required|in:development,management_qa,qa,management','condition'=>'sometimes|required|in:ok,damaged,needs_repair','comment'=>'nullable|string','purchased_on'=>'nullable|date','purchase_cost'=>'nullable|numeric|min:0','useful_life_months'=>'nullable|integer|min:1|max:600','cpu'=>'nullable|string|max:200','ram'=>'nullable|string|max:100','storage'=>'nullable|string|max:200','gpu'=>'nullable|string|max:200','os'=>'nullable|string|max:100','os_version'=>'nullable|string|max:100','imei'=>'nullable|string|max:32'])->validate(); DB::table('equipment_items')->where('id',$id)->update(array_merge($v,['updated_at'=>now()])); equipmentAudit($id,'updated',$r,$v); return response()->json(['data'=>equipmentDecorate(DB::table('equipment_items')->find($id))]); });
Route::post('/items/{id}/assign', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); if($item->written_off_at)return response()->json(['message'=>'Written-off equipment cannot be assigned'],409); if(DB::table('equipment_assignments')->where('equipment_item_id',$id)->whereNull('returned_on')->exists())return response()->json(['message'=>'Equipment already assigned'],409); $v=Validator::make($r->all(),['employee_id'=>'required|integer|min:1','starts_on'=>'required|date','planned_ends_on'=>'nullable|date|after_or_equal:starts_on','issue_comment'=>'nullable|string'])->validate(); $employeeBase=rtrim((string)env('EMPLOYEES_URL','http://employees:8000/api'),'/'); try{$check=Http::withHeaders(['X-Irlix-Access-Token'=>$r->bearerToken() ?: $r->header('X-Irlix-Access-Token')])->timeout(4)->get("{$employeeBase}/employees/{$v['employee_id']}"); if(!$check->successful())return response()->json(['message'=>'Employee not found or Employees unavailable'],422);}catch(\Throwable){return response()->json(['message'=>'Employees service unavailable'],503);} $assignment=array_merge($v,['equipment_item_id'=>$id,'issued_by'=>equipmentActor($r),'created_at'=>now(),'updated_at'=>now()]); $aid=DB::table('equipment_assignments')->insertGetId($assignment); equipmentAudit($id,'assigned',$r,['assignment_id'=>$aid,'employee_id'=>$v['employee_id'],'starts_on'=>$v['starts_on'],'planned_ends_on'=>$v['planned_ends_on']??null]); return response()->json(['data'=>DB::table('equipment_assignments')->find($aid)],201); });
Route::post('/items/{id}/return', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $a=DB::table('equipment_assignments')->where('equipment_item_id',$id)->whereNull('returned_on')->first(); if(!$a)return response()->json(['message'=>'No active assignment'],409); $v=Validator::make($r->all(),['returned_on'=>'required|date|after_or_equal:'.$a->starts_on,'return_comment'=>'nullable|string'])->validate(); DB::table('equipment_assignments')->where('id',$a->id)->update(['returned_on'=>$v['returned_on'],'returned_by'=>equipmentActor($r),'return_comment'=>$v['return_comment']??null,'updated_at'=>now()]); equipmentAudit($id,'returned',$r,['assignment_id'=>$a->id,'returned_on'=>$v['returned_on']]); return response()->json(['data'=>DB::table('equipment_assignments')->find($a->id)]); });
Route::post('/items/{id}/write-off', function(Request $r,int $id){ if($g=equipmentGuard(equipmentCanOperate($r)))return $g; $item=DB::table('equipment_items')->find($id); if(!$item)return response()->json(['message'=>'Not found'],404); if($item->written_off_at)return response()->json(['message'=>'Already written off'],409); if(DB::table('equipment_assignments')->where('equipment_item_id',$id)->whereNull('returned_on')->exists())return response()->json(['message'=>'Return equipment before write-off'],409); $v=Validator::make($r->all(),['written_off_on'=>'required|date','reason'=>'required|string|max:500','comment'=>'nullable|string'])->validate(); $dep=equipmentDepreciation($item,Carbon::parse($v['written_off_on'])); DB::transaction(function()use($id,$v,$dep,$r){DB::table('equipment_items')->where('id',$id)->update(['written_off_at'=>$v['written_off_on'],'updated_at'=>now()]); DB::table('equipment_write_offs')->insert(['equipment_item_id'=>$id,'written_off_on'=>$v['written_off_on'],'reason'=>$v['reason'],'comment'=>$v['comment']??null,'actor'=>equipmentActor($r),'residual_value'=>$dep['residual'],'created_at'=>now(),'updated_at'=>now()]); equipmentAudit($id,'written_off',$r,['written_off_on'=>$v['written_off_on'],'reason'=>$v['reason'],'residual_value'=>$dep['residual']]);}); return response()->json(['data'=>equipmentDecorate(DB::table('equipment_items')->find($id))]); });
Route::get('/assignments', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; $rows=DB::table('equipment_assignments as a')->join('equipment_items as i','i.id','=','a.equipment_item_id')->select('a.*','i.inventory_number','i.manufacturer','i.model','i.type')->orderByDesc('a.starts_on')->get(); return response()->json(['data'=>$rows]); });
Route::get('/depreciation', function(Request $r){ if($g=equipmentGuard(equipmentCanView($r)))return $g; return response()->json(['data'=>DB::table('equipment_items')->orderBy('inventory_number')->get()->map(function($i){$x=(array)$i;return ['id'=>$i->id,'inventory_number'=>$i->inventory_number,'manufacturer'=>$i->manufacturer,'model'=>$i->model,'purchase_cost'=>(float)($i->purchase_cost??0),'written_off_at'=>$i->written_off_at,'depreciation'=>equipmentDepreciation($x)];})]); });
